name: Benchmark
on:
  push:
    branches: ["gh-actions-bench"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Benchmark
    env:
      MIX_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: 27.x
          elixir-version: 1.18.x
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: cache-v4-${{steps.setup-beam.outputs.elixir-version}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            cache-v4-${{steps.setup-beam.outputs.elixir-version}}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
      - name: Run
        run: mix run bench/nonces.exs
