name: CI / Automated testing
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }} on ${{ matrix.os }}
    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432
      mysql:
        image: mysql:debian
        env:
          MYSQL_ROOT_PASSWORD: supersecret
        ports:
          - 3306:3306

    strategy:
      # https://hexdocs.pm/elixir/1.20/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      fail-fast: false
      matrix:
        include:
          # soft support floor
          - elixir: 1.16.x
            otp: 25.x
            os: ubuntu-latest
            command: mix test
          # hard support floor (current minus 2)
          - elixir: 1.18.x
            otp: 27.x
            os: ubuntu-latest
            command: mix test
          # support ceiling
          - elixir: 1.20.x
            otp: 29.x
            os: ubuntu-latest
            command: mix test

    steps:
      - &checkout
        name: Checkout code
        uses: actions/checkout@v7
      - &setup-beam
        uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - &cache-deps
        name: Cache deps
        id: cache
        uses: actions/cache@v6
        with:
          path: |
            deps
            _build
          key: cache-v6-${{ matrix.os }}-${{steps.setup-beam.outputs.elixir-version}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            cache-v6-${{ matrix.os }}-${{steps.setup-beam.outputs.elixir-version}}-
      - &install-dependencies
        name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
      - name: Check code formatting
        if: matrix.elixir == '1.20.x' && matrix.os == 'ubuntu-latest'
        run: mix format --check-formatted
      - &compile-dependencies
        name: Compile dependencies
        run: mix deps.compile
      - &compile-code
        name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: ${{ matrix.command }}
      - name: Node shutdown on machine ID conflict test
        run: ./test/test_conflict_guard.sh
        if: matrix.os == 'ubuntu-latest'
      - name: Create docs
        if: matrix.elixir == '1.20.x' && matrix.os == 'ubuntu-latest'
        run: mix docs

  test-unit:
    runs-on: ${{ matrix.os }}
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }} on ${{ matrix.os }}
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          # MS crap
          - elixir: 1.16.x
            otp: 25.x
            os: windows-2022
          - elixir: 1.20.x
            otp: 29.x
            os: windows-2022
          # Apple crap
          - elixir: 1.16.x
            otp: 25.x
            os: macos-latest
          - elixir: 1.20.x
            otp: 29.x
            os: macos-latest
    steps:
      - *checkout
      - *setup-beam
      - *cache-deps
      - *install-dependencies
      - *compile-dependencies
      - *compile-code
      - name: Run unit tests
        run: mix test.unit --exclude blowfish
